### ISSUE TITLE
ff ls command

### ISSUE THREAD

**Issue by nguyer** [hyperledger-labs/firefly-cli#25]
We should add an `ff ls` command to list the stacks that currently exist. It would also be nice to indicate if any of them are running or not.

**Comment by awrichar** [comment]
+1, although would suggest `ff list` instead

**Comment by nguyer** [comment]
> +1, although would suggest `ff list` instead

That's a really good point... it would be more consistent with our other commands. I would love to add short hand aliases at some point so I can also do `rm`. Because I type that a lot and my CLI has no idea what I mean...

For now though, the functionality was added in https://github.com/hyperledger-labs/firefly-cli/pull/29
