### ISSUE TITLE
Errors from wrapped commands should be surfaced more clearly

### ISSUE THREAD

**Issue by awrichar** [hyperledger-labs/firefly-cli#27]
If any of the docker/docker-compose commands wrapped by `ff` exit with an error (non-zero) status, this should be treated as an error and surfaced by the CLI. Currently it checks for errors at the Go level but does not check exit codes.

**Comment by nguyer** [comment]
This has been resolved in https://github.com/hyperledger-labs/firefly-cli/pull/28
