### ISSUE TITLE
Nodes sometimes fail to self-register on startup

### ISSUE THREAD

**Issue by awrichar** [hyperledger-labs/firefly-cli#33]
When running `ff start`, nodes intermittently fail to register with the following error:

```
Post "http://localhost:5000/api/v1/network/register/node/organization": dial tcp 127.0.0.1:5000: connect: connection refused
```

Furthermore, the registration is not re-attempted on subsequent starts, so you generally have to remove and recreate the stack.

**Comment by nguyer** [comment]
Do we have a reliable way of reproducing this behavior? I know some folks have seen it a lot, but I haven't been able to reproduce this issue on my machine. Perhaps we should re-test on the newest CLI now that we have a few more fixes in?

**Comment by nguyer** [comment]
I think this is probably fixed now. I haven't seen it happening in any of the latest versions of the CLI. If you're still seeing this, please re-open. Thanks!
