### ISSUE TITLE
Postgres Containers showing fatal permission issue on creation/startup

### ISSUE THREAD

**Issue by zts3y** [hyperledger-labs/firefly-cli#34]
### Expected Behavior
`ff start [stack_name]` should start up stack completely per user prompted information

### Current Behavior
Upon initializing the stack and issuing the `ff start [stack_name]` command, containers are spinning up but the postgres containers are failing with apparent permissions errors which cause other containers to fail due to inability to connect to the database container.
![image](https://user-images.githubusercontent.com/42187698/121722377-61945580-cab3-11eb-9b02-bce89d0b6959.png)

### Context (Environment)
- OS: Windows 10
- Terminal: Git Bash
- Go version: go1.16.5 windows/amd64
- Docker version: 20.10.6
- Firefly versions:
![image](https://user-images.githubusercontent.com/42187698/121723438-8210df80-cab4-11eb-87fd-f14fb264b072.png)

### Attempted Manual Corrections
I have executed `chmod -R 0755 ~/.firefly/stacks/[stack_name]/data/postgres_[N]` on each of the indicated node folders.

**Comment by nguyer** [comment]
Thanks for reporting this @zts3y! I don't have immediate access to a Windows machine to debug this, but I can try to set it up on a VM or something. Or if you happen to figure out the fix, you're welcome to open a PR. Testing on Windows is one of the areas we know we need to do more work on.

**Comment by nguyer** [comment]
Quick question, as I'm trying to reproduce this...

Are you running the Hyper-V or WSL2 engine for Docker on Windows?

**Comment by nguyer** [comment]
@zts3y Quick question, as I'm trying to reproduce this...

Are you running the Hyper-V or WSL2 engine for Docker on Windows?

**Comment by zts3y** [comment]
@nguyer Using Hyper-V for this as the version of Windows 10 Enterprise I have isn't compatible with WSL2.

**Comment by nguyer** [comment]
This should be fixed now. Please feel free to re-open if you're still running into this issue.

**Comment by zts3y** [comment]
Just wanted to confirm for you that the latest version stood up perfectly @nguyer .
