### ISSUE TITLE
ff remove <stack_name> , doesn't remove stack

### ISSUE THREAD

**Issue by ksanjaykumar1** [hyperledger-labs/firefly-cli#36]
the command is not deleting local data and configuration even after executing the command
![Screenshot from 2021-06-12 20-21-07](https://user-images.githubusercontent.com/72605368/121781455-701d6280-cbc2-11eb-949c-7ab88908b9da.png)

**Comment by nguyer** [comment]
@ksanjaykumar1 Can you tell me a little bit more about your dev environment? Do you run docker as `root` or with `sudo` or is your user set up to be able to run docker directly?

It looks like somehow something in the `data` directory for that stack got created with different permissions (I'm guessing as `root`) but `ff` is running as your user, so is unable to delete it.

If I run `ff` with `sudo` the `remove` command does work for me.

**Comment by nguyer** [comment]
This should be fixed now. Please feel free to re-open if you're still running into this issue.
